name: Build Windows Portable

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build Windows portable
      run: npm run build:win
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload Windows Portable
      uses: actions/upload-artifact@v3
      with:
        name: Softwrap-POS-Windows-Portable
        path: |
          dist/*.exe
          !dist/*Setup*.exe
        retention-days: 90
        
    - name: Upload Windows Installer
      uses: actions/upload-artifact@v3
      with:
        name: Softwrap-POS-Windows-Installer
        path: dist/*Setup*.exe
        retention-days: 90

